		
tailwind-old:
	tailwindcss -i ./views/css/main.css -o ./public/css/main.css
		
tailwind-watch-old:
	tailwindcss -i ./views/css/main.css -o ./public/css/main.css --watch



tailwind:
	npx @tailwindcss/cli -i ./views/css/main.css -o ./public/css/main.css
	
tailwind-watch:
	npx @tailwindcss/cli -i ./views/css/main.css -o ./public/css/main.css --watch