services:
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui
    ports: 
     - 2053:2053
     - 2096:2096
    volumes:
      - db:/etc/x-ui/
      - cert:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    tty: true
    # network_mode: host
    restart: unless-stopped

volumes:
  db:
  cert: