root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # args_bin = ["-env", "../../.env", "-storage", "../../internal/storage/sqlite/test_data/db.db"]
  bin = "tmp\\admin.exe"
  cmd = "make -j3 admin-prepare & go build -o ./tmp/admin.exe ./cmd/admin"
  delay = 1000
  exclude_dir = [".git", "assets", "tmp", "vendor", "testdata",
     "node_modules", "public", "web\\3x-ui", "web\\admin_panel\\node_modules",
     "pkg\\clients\\x-ui\\api", "cmd\\admin\\tmp", "web\\admin_panel\\api",
     "watching web\\admin_panel\\public\\dest"
    ]
  exclude_file = []
  exclude_regex = ["_test.go", ".*_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "tmpl", "templ", "css", "ts"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
